# to accept the days of the week & display the day/s with min temp 
# here the weekday names should be generated by prog itself
# (coolest day/s)
import calendar
daily_temps = {}   # dictionary

l = list(calendar.day_abbr)

for i in range(7):
	temp = int(input("Enter the temp for "+l[i]+" :- "))
	daily_temps[l[i]] = temp

# m = min(daily_temps.values())    # short cut, name of var should not be
			# that of a function

# goal is to find the min temp first
m = list(daily_temps.values())[0]

for key in daily_temps.keys():
	if m > daily_temps[key]:
		m = daily_temps[key]

# display all months and temps where temp = m
print("Days & temps are")
for key in daily_temps.keys():
	if m == daily_temps[key]:
		print(key," - ",daily_temps[key])






